#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#########################################################################################################################################
######################## Pruebas entrutado
#########################################################################################################################################
ruta_request_get:
  path: /enrutado/prueba-request-get/{valorentero}/{pordefecto}/
  controller: App\Controller\Enrutado\PruebaRequestGetController
  methods: ['GET']
  defaults:
    pordefecto: 'valorpordefecto'
  requirements:
    valorentero: '\d+'

ruta_request_get_con_querystring:
  path: /enrutado/prueba-request-get-querystring/
  methods: 'GET'
  controller: App\Controller\Enrutado\PruebaRequestGetQueryStringController

ruta_request_post_con_headers:
  path: /enrutado/prueba-request-post-headers/
  methods: POST
  controller: App\Controller\Enrutado\PruebaRequestPostHeadersController

ruta_request_put_content:
  path: /enrutado/prueba-request-put-content/
  methods: PUT
  controller: App\Controller\Enrutado\PruebaRequestPutContentController

ruta_request_funciones_put:
  path: /enrutado/prueba-funciones-put/ruta/hacia/controller/
  methods: PUT
  controller: App\Controller\Enrutado\PruebaRequestFuncionesPutController

#########################################################################################################################################
######################## Pruebas AbstractController
#########################################################################################################################################
ruta_generar_rutas:
  path: /abstractcontroller/generar-rutas/
  controller: App\Controller\AbstractController\GeneracionRutasController
  methods: POST

ruta_generada_get:
  path: /abstractcontroller/ruta-generada-get/{parametrostring1}/{valorPorDefecto}/{paramtronumerico1}/{parametrostring2}/
  controller: App\Controller\AbstractController\RutasGeneradas\RutaGeneradaGetController
  methods: GET
  defaults:
    valorPorDefecto: 'valorpordefecto'

ruta_generada_post:
  path: /abstractcontroller/ruta-generada-post/{valorpordefecto}/
  controller: App\Controller\AbstractController\RutasGeneradas\RutaGeneradaPostController
  methods: POST
  defaults:
    valorpordefecto: 'pordefecto'

#########################################################################################################################################
######################## Pruebas redis
#########################################################################################################################################
ruta_redis_clave_valor:
  path: /redis/set/clavevalor/
  methods: POST
  controller: App\Controller\Redis\PrubaClaveValorController
