# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

imports:
    # glob expressions are also supported to load multiple files
    #- { resource: '/etc/myapp/*.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

#    App\Services\Redis\ConectarRedis:
#        arguments:
#            $scheme: 'env(%REDIS_SCHEME%)'
#            $host: 'env(%REDIS_HOST%)'
#            $port: 'env(%REDIS_PORT%)'
#            $database: 'env(%REDIS_DATABASE%)'
#
#    App\Services\Redis\DesconectarRedis:
#
#    App\Services\Redis\GuardarClaveValorRedis:
#        arguments:
#            $conectarRedis: '@App\Services\Redis\ConectarRedis'
#            $desconectarRedis: '@App\Services\Redis\DesconectarRedis'
#
#    App\Controller\Redis\AgregarClaveValorRedisController:
#        arguments:
#            $guardarClaveValorRedis: '@App\Services\Redis\GuardarClaveValorRedis'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
